### PR TITLE
updated to jQuery 1.8.0

### PR DESCRIPTION
**Pull request by delight**
http://blog.jquery.com/2012/08/09/jquery-1-8-released/

### CODE REVIEW

**Comment by jameskleeh** [comment]
Fantastic! Merge that to the branch!

**Comment by matthiaswenz** [comment]
Please merge that!

**Comment by aditzel** [comment]
It would be great if this could be merged in.

**Comment by delight** [comment]
closing this as @robfletcher did his own commit to upgrade to 1.8.0

**Pull request closed without merging**
