### PR TITLE
added missing .min.map file - fixes http://jira.grails.org/browse/GPJQUERY-60

### PR DESCRIPTION
**Pull request by dtanner**

### CODE REVIEW

**Comment by joeRinehart** [comment]
+1 - Please merge this in

**Comment by morungos** [comment]
+1 from me too - the missing file triggers log error noise in Chrome

**Comment by mdeimel** [comment]
+1 in agreement with others

**Comment by photusenigma** [comment]
+1 agreed...Please!

**Comment by bobbywarner** [comment]
@dtanner @joeRinehart @morungos @mdeimel @photusenigma Looks like jQuery 1.11 is coming soon as the first beta was just released (http://blog.jquery.com/2013/09/19/jquery-1-11-and-2-1-beta-1-released/).  So, I'm going to close this pull request and I'll make sure that the min.map file is included in the next release of the plugin with jQuery 1.11.  Thanks!

**Comment by bobbywarner** [comment]
@dtanner @joeRinehart @morungos @mdeimel @photusenigma The release of jQuery 1.11 is taking way longer than I would have thought.  I'll apply this change and release a point release (1.10.2.1).

**Pull request merged**
