### PR TITLE
Add jQuery source mapping file to support developer tools.

### PR DESCRIPTION
**Pull request by lyhcode**
It's a new feature in current jQuery versions. Without this .min.map file, browser console will show a 404 error.

### CODE REVIEW

**Comment by confile** [comment]
+1 for the pull request

When will it be merged!!!

**Comment by bobbywarner** [comment]
Thanks.  It was added in another pull request (https://github.com/gpc/grails-jquery/pull/23) and is included in version 1.10.2.1 of the plugin.

**Comment by confile** [comment]
Plugin 1.10.2.1 is not working resource mismatch: http://jira.grails.org/browse/GPJQUERY-60

**Comment by bobbywarner** [comment]
@confile Sorry about that.  Please try version 1.10.2.2

**Pull request closed without merging**
