### PR TITLE
Added support for asset-pipeline inclusion

### PR DESCRIPTION
**Pull request by davydotcom**
Users of grails asset-pipeline plugin can simply include js into their app.js by doing:

``` javascript
//= require jquery

$(document).ready(function() {
  console.log("Yay! I have jQuery");
});
```

### CODE REVIEW

**Comment by tbarker9** [comment]
:thumbsup:

**Comment by alex88** [comment]
+1

**Comment by bobbywarner** [comment]
@davydotcom Thanks!

**Comment by davydotcom** [comment]
woah forgot about this! :)

**Comment by zyro23** [comment]
should jquery.js not be placed into a sub-directory of grails-app/assets (e.g. grails-app/assets/javascripts)?

it looks like a direct include via `<asset:javascript src="jquery.js" />` does not work for files directly inside the assets directory, but only for files at least one level deeper.

is this observation even correct? thanks, zyro

**Comment by davydotcom** [comment]
gooood call, whoops!

**Pull request merged**
